export const KEYBOARD_SHORTCUTS = {
  TOGGLE_SIDEBAR: "toggle_sidebar",
  TOGGLE_UPLOAD_MODAL: "toggle_upload_modal",
  TOGGLE_KEYBOARD_SHORTCUT_MODAL: "toggle_keyboard_shortcut_modal",
  EXIT_INPUT_FOCUS: "exit_input_focus",

  NAVIGATE_HOME: "navigate_home",
  NAVIGATE_SEARCH: "navigate_search",
  NAVIGATE_PROFILE: "navigate_profile",
  NAVIGATE_MANAGE_SONGS: "navigate_manage_songs",
  NAVIGATE_MANAGE_PLAYLISTS: "navigate_manage_playlists",
  NAVIGATE_MANAGE_FOLLOWING: "navigate_manage_following",
  NAVIGATE_MANAGE_NOTIFICATIONS: "navigate_manage_notifications",
  NAVIGATE_SETTINGS_ACCOUNT: "navigate_settings_account",
  NAVIGATE_SETTINGS_NOTIFICATIONS: "navigate_settings_notifications",
  NAVIGATE_SETTINGS_LANGUAGE: "navigate_settings_language",
  NAVIGATE_SETTINGS_CONNECTED_DEVICES: "navigate_settings_connected_devices",

  TOGGLE_PLAYBACK: "toggle_playback",
  TOGGLE_SHUFFLE: "toggle_shuffle",
  CYCLE_REPEAT: "cycle_repeat",
  NEXT: "next_track",
  PREVIOUS: "previous_track",
  SEEK_FORWARD: "seek_forward",
  SEEK_BACKWARD: "seek_backward",
  RAISE_VOLUME: "raise_volume",
  LOWER_VOLUME: "lower_volume",
  TOGGLE_MUTE: "toggle_mute",
  INCREASE_SPEED: "increase_speed",
  DECREASE_SPEED: "decrease_speed",
  STOP_AUDIO: "stop_audio",
} as const;
